#!/bin/sh

ETDB_ADDONS=

echo "Parsing New Modules"

for option
do
  case $option in
    --add-module=*)   ETDB_ADDONS="$ETDB_ADDONS $value";;
    *)  
       echo "$0: error: invalid option \"$option\"" 
       exit 1
    ;; 
  esac
done
