#!/bin/sh

echo "Prepare Sources"

ETDB_INCS="src \
           src/store \
           src/modules \
           api/c \
           deps/jemalloc-3.6.0/include"

cp src/store/etdb_queue.h  api/c -f
cp src/store/etdb_string.h api/c -f
cp src/store/etdb_bytes.h  api/c -f

ETDB_LIB_SRCS="src/etdb_buf.c \
               src/etdb_config.c \
               src/etdb_file_config.c \
               src/etdb_connection.c \
               src/etdb_geo_hash.c \
               src/etdb_modules.c \
               src/etdb_resp.c \
               src/etdb_serv.c \
               src/etdb_event.c \
               src/etdb_database.c \
               src/hietdb.c \
               src/linenoise.c \
               src/store/etdb_queue.c \
               src/store/etdb_alloc.c \
               src/store/etdb_palloc.c \
               src/store/etdb_log.c \
               src/store/etdb_time.c \
               src/store/etdb_bytes.c \
               src/store/etdb_stack.c \
               src/store/etdb_string.c \
               src/store/etdb_lru.c \
               src/store/etdb_trie.c \
               src/store/etdb_store.c \
               src/modules/etdb_kv.c \
               src/modules/etdb_hash.c \
               src/modules/etdb_list.c \
               src/modules/etdb_set.c \
               src/modules/etdb_spatial_point.c \
               src/modules/etdb_sys.c"

ETDB_TEST_SRCS="test/etdb_test_alloc.c \
                test/etdb_test_string.c \
                test/etdb_test_trie_erase.c \
                test/etdb_test_trie_search.c \
                test/etdb_test_trie_update.c \
                test/etdb_test_client.c \
                test/etdb_test_store.c"

mkdir -p $ETDB_OBJS

### Generate etdb_modules.c File
cat << END > src/etdb_modules.c

#include <etdb.h>

extern etdb_module_t etdb_kv_module;
extern etdb_module_t etdb_hash_module;
extern etdb_module_t etdb_list_module;
extern etdb_module_t etdb_set_module;
extern etdb_module_t etdb_sidx_module;
extern etdb_module_t etdb_sys_module;

etdb_module_t* etdb_modules[]={
  &etdb_kv_module,
  &etdb_hash_module,
  &etdb_list_module,
  &etdb_set_module,
  &etdb_sidx_module,
  &etdb_sys_module,
  NULL
};

END


