#!/bin/sh

echo "Prepare Sources"

ETDB_INCS="src \
           src/modules"

ETDB_LIB_SRCS="src/etdb_alloc.c \
               src/etdb_buf.c \
               src/etdb_config.c \
               src/etdb_file_config.c \
               src/etdb_connection.c \
               src/etdb_event.c \
               src/etdb_queue.c \
               src/etdb_bytes.c \
               src/etdb_geo_hash.c \
               src/etdb_log.c \
               src/etdb_modules.c \
               src/etdb_palloc.c \
               src/etdb_resp.c \
               src/etdb_serv.c \
               src/etdb_stack.c \
               src/etdb_string.c \
               src/etdb_time.c \
               src/etdb_trie.c \
               src/etdb_database.c \
               src/linenoise.c \
               src/modules/etdb_kv.c \
               src/modules/etdb_hash.c "

ETDB_TEST_SRCS="test/etdb_test_alloc.c \
                test/etdb_test_string.c \
                test/etdb_test_trie_erase.c \
                test/etdb_test_trie_search.c \
                test/etdb_test_trie_update.c"

mkdir -p $ETDB_OBJS

### Generate etdb_modules.c File
cat << END > src/etdb_modules.c

#include <etdb.h>

extern etdb_module_t etdb_kv_module;

etdb_module_t* etdb_modules[]={
  &etdb_kv_module,
  NULL
};

END


